spring.application.name=session_4
#Database
spring.datasource.url= jdbc:postgresql://localhost:5432/course-management
spring.datasource.username = postgres
spring.datasource.password = 1234
#JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto= update
#SQL
spring.jpa.show-sql=true
#DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
